# Generated by Django 5.0.6 on 2024-09-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
    ]
