# Generated by Django 5.0.6 on 2024-09-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0002_alter_account_age_alter_account_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
